on:
  workflow_run:
    workflows: [scenario-server]
    types: [completed]
  push:
    paths:
      - javascript-effection/**
      - .github/workflows/javascript-effection.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - working-directory: ./javascript-effection
        run: |
          deno task test
          npm install
          npm test
