---
on:
  workflow_run:
    workflows: [scenario-server]
    types: [completed]
  push:
    paths:
      - ocaml-cohttp-eio/**
      - .github/workflows/ocaml-cohttp-eio.yaml
  pull_request:
    paths:
      - ocaml-cohttp-eio/**
      - .github/workflows/ocaml-cohttp-eio.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set-up OCaml 5.1
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.1
          dune-cache: true

      - name: Run tests
        working-directory: ./ocaml-cohttp-eio
        run: |
          opam install . --deps-only --with-test
          ulimit -n 16000
          opam exec -- dune runtest --force
