---
on:
  workflow_run:
    workflows: [scenario-server]
    types: [completed]
  push:
    paths:
      - ocaml-cohttp-lwt/**
      - .github/workflows/ocaml-cohttp-lwt.yaml
  pull_request:
    paths:
      - ocaml-cohttp-lwt/**
      - .github/workflows/ocaml-cohttp-lwt.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set-up OCaml 5.1
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.1
          dune-cache: true

      - name: Install libev
        run: sudo apt install libev4 libev-dev

      - name: Run tests
        working-directory: ./ocaml-cohttp-lwt
        run: |
          ulimit -n 16000
          opam install . --deps-only --with-test
          opam exec -- dune build
          opam exec -- dune runtest
